version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd frontend
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  # The base-directory is the final build output
  base-directory: 'frontend/build'
  files:
    - '**/*'