version: 0.2
phases:
  build:
    commands:
      - echo "No build steps needed for backend, just packaging..."
artifacts:
  base-directory: 'backend'
  files:
    - 'app.py'
    - 'requirements.txt'
    - 'appspec.yml' # This now refers to backend/appspec.yml
    - 'scripts/**/*' # This now refers to backend/scripts/
    - '.env' 