version: 0.2
phases:
  build:
    commands:
      - echo "No build steps needed for backend, just packaging..."
artifacts:
  # This tells CodeBuild to look for files inside the 'backend' directory
  base-directory: 'backend'
  files:
    - 'app.py'
    - 'requirements.txt'
    - 'appspec.yml' # This now refers to backend/appspec.yml
    - 'scripts/**/*' # This now refers to backend/scripts/
    - '.env' 